/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as RiseRouteImport } from './routes/rise'
import { Route as ParkingLotRouteImport } from './routes/parking-lot'
import { Route as LandRouteImport } from './routes/land'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as IndexRouteImport } from './routes/index'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const RiseRoute = RiseRouteImport.update({
  id: '/rise',
  path: '/rise',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingLotRoute = ParkingLotRouteImport.update({
  id: '/parking-lot',
  path: '/parking-lot',
  getParentRoute: () => rootRouteImport,
} as any)
const LandRoute = LandRouteImport.update({
  id: '/land',
  path: '/land',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/land': typeof LandRoute
  '/parking-lot': typeof ParkingLotRoute
  '/rise': typeof RiseRoute
  '/today': typeof TodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/land': typeof LandRoute
  '/parking-lot': typeof ParkingLotRoute
  '/rise': typeof RiseRoute
  '/today': typeof TodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand': typeof BrandRoute
  '/land': typeof LandRoute
  '/parking-lot': typeof ParkingLotRoute
  '/rise': typeof RiseRoute
  '/today': typeof TodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/brand' | '/land' | '/parking-lot' | '/rise' | '/today'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/brand' | '/land' | '/parking-lot' | '/rise' | '/today'
  id:
    | '__root__'
    | '/'
    | '/brand'
    | '/land'
    | '/parking-lot'
    | '/rise'
    | '/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandRoute: typeof BrandRoute
  LandRoute: typeof LandRoute
  ParkingLotRoute: typeof ParkingLotRoute
  RiseRoute: typeof RiseRoute
  TodayRoute: typeof TodayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rise': {
      id: '/rise'
      path: '/rise'
      fullPath: '/rise'
      preLoaderRoute: typeof RiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parking-lot': {
      id: '/parking-lot'
      path: '/parking-lot'
      fullPath: '/parking-lot'
      preLoaderRoute: typeof ParkingLotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/land': {
      id: '/land'
      path: '/land'
      fullPath: '/land'
      preLoaderRoute: typeof LandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandRoute: BrandRoute,
  LandRoute: LandRoute,
  ParkingLotRoute: ParkingLotRoute,
  RiseRoute: RiseRoute,
  TodayRoute: TodayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
