// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wuzfyniadmkvrqhqgxyy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1emZ5bmlhZG1rdnJxaHFneHl5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI5OTI1OTYsImV4cCI6MjA5ODU2ODU5Nn0.rY4rAGHOJGNctU1EfQp7iKakTisTsHzZFEbAI2JIagk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});